import { Injectable } from '@angular/core';
import * as XLSX from 'xlsx';

export interface ExportTable {
  sheetName: string;
  title:     string;
  headers:   string[];
  rows:      (string | number)[][];
}

export interface ReportExportConfig {
  reportName:  string;
  restaurant:  string;
  branch:      string;
  dateRange:   { from: string; to: string };
  generatedBy: string;
  stats:       { metric: string; value: string; change: string; positive: boolean }[];
  insights:    string[];
  alerts:      string[];
  tables:      ExportTable[];
}

@Injectable({ providedIn: 'root' })
export class ReportExportService {

  /* ═══════════════════════════════════════════
     PDF  (browser print — no external library)
  ═══════════════════════════════════════════ */
  exportToPDF(cfg: ReportExportConfig): void {
    const now    = new Date().toLocaleString('en-IN', { dateStyle: 'medium', timeStyle: 'short' });
    const html   = this.buildPrintHTML(cfg, now);
    const win    = window.open('', '_blank', 'width=900,height=700');
    if (!win) { alert('Allow popups to export PDF.'); return; }
    win.document.open();
    win.document.write(html);
    win.document.close();
    win.focus();
    setTimeout(() => { win.print(); }, 800);
  }

  /* ═══════════════════════════════════════════
     EXCEL  (xlsx — multi-sheet)
  ═══════════════════════════════════════════ */
  exportToExcel(cfg: ReportExportConfig): void {
    const wb  = XLSX.utils.book_new();
    const now = new Date().toLocaleString('en-IN', { dateStyle: 'medium', timeStyle: 'short' });

    // ── Sheet 1: Summary ────────────────────
    const summaryRows: (string | number)[][] = [
      ['Kitchen Book – ' + cfg.reportName],
      [],
      ['Restaurant',   cfg.restaurant],
      ['Branch',       cfg.branch],
      ['Date Range',   cfg.dateRange.from + ' to ' + cfg.dateRange.to],
      ['Generated On', now],
      ['Generated By', cfg.generatedBy],
      [],
      ['── KPI SUMMARY ──'],
      ['Metric', 'Value', 'Change'],
      ...cfg.stats.map(s => [s.metric, s.value, s.change]),
      [],
      ['── INSIGHTS ──'],
      ...cfg.insights.map(i => ['• ' + i]),
      [],
      ['── ALERTS ──'],
      ...cfg.alerts.map(a => ['⚠  ' + a]),
    ];
    const ws1 = XLSX.utils.aoa_to_sheet(summaryRows);
    ws1['!cols'] = [{ wch: 28 }, { wch: 22 }, { wch: 16 }];
    XLSX.utils.book_append_sheet(wb, ws1, 'Summary');

    // ── Remaining sheets from tables ────────
    cfg.tables.forEach(t => {
      const sheetData: (string | number)[][] = [
        [t.title],
        [],
        t.headers,
        ...t.rows,
      ];
      const ws = XLSX.utils.aoa_to_sheet(sheetData);
      ws['!cols'] = t.headers.map(() => ({ wch: 18 }));
      // Merge title row across all columns
      ws['!merges'] = [{ s: { r: 0, c: 0 }, e: { r: 0, c: t.headers.length - 1 } }];
      XLSX.utils.book_append_sheet(wb, ws, t.sheetName.slice(0, 31));
    });

    XLSX.writeFile(wb, cfg.reportName.replace(/[^a-zA-Z0-9 ]/g, '') + '.xlsx');
  }

  /* ═══════════════════════════════════════════
     Private: build print HTML
  ═══════════════════════════════════════════ */
  private buildPrintHTML(cfg: ReportExportConfig, now: string): string {
    const kpiRows = cfg.stats.map(s => `
      <div class="kpi-card">
        <div class="kpi-value">${s.value}</div>
        <div class="kpi-label">${s.metric}</div>
        <div class="kpi-change ${s.positive ? 'pos' : 'neg'}">${s.change}</div>
      </div>`).join('');

    const insightRows = cfg.insights.map(i => `<div class="insight-row">• ${i}</div>`).join('');
    const alertRows   = cfg.alerts.map(a   => `<div class="alert-row">⚠ ${a}</div>`).join('');

    const tableSections = cfg.tables.map(t => `
      <div class="section">
        <h3 class="section-title">${t.title}</h3>
        <table>
          <thead><tr>${t.headers.map(h => `<th>${h}</th>`).join('')}</tr></thead>
          <tbody>${t.rows.map(r => `<tr>${r.map(c => `<td>${c}</td>`).join('')}</tr>`).join('')}</tbody>
        </table>
      </div>`).join('<div class="page-break"></div>');

    return `<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<title>${cfg.reportName} – Kitchen Book</title>
<style>
  @page { size: A4; margin: 14mm 16mm; }
  * { box-sizing: border-box; margin: 0; padding: 0; }
  body { font-family: Arial, Helvetica, sans-serif; font-size: 10pt; color: #1e293b; }

  /* Header */
  .hdr { background: #1e3a5f; color: #fff; padding: 18px 20px; border-radius: 0 0 8px 8px; }
  .hdr h1 { font-size: 18pt; font-weight: 800; letter-spacing: -0.3px; }
  .hdr .sub { font-size: 9pt; opacity: .75; margin-top: 2px; }
  .meta-grid { display: grid; grid-template-columns: repeat(3,1fr); gap: 6px; margin-top: 14px; }
  .meta-item { background: rgba(255,255,255,.12); border-radius: 6px; padding: 7px 10px; }
  .meta-item .mk { font-size: 7pt; text-transform: uppercase; letter-spacing: .5px; opacity: .7; }
  .meta-item .mv { font-size: 9pt; font-weight: 700; margin-top: 1px; }

  /* KPI */
  .section { margin-top: 18px; }
  .section-title { font-size: 10pt; font-weight: 800; color: #1e3a5f; text-transform: uppercase; letter-spacing: .5px; border-bottom: 2px solid #1e3a5f; padding-bottom: 4px; margin-bottom: 10px; }
  .kpi-grid { display: grid; grid-template-columns: repeat(4,1fr); gap: 8px; }
  .kpi-card { border: 1px solid #e2e8f0; border-radius: 8px; padding: 10px 12px; background: #f8fafc; }
  .kpi-value { font-size: 14pt; font-weight: 800; color: #1e3a5f; }
  .kpi-label { font-size: 7pt; text-transform: uppercase; color: #94a3b8; letter-spacing: .5px; margin-top: 2px; }
  .kpi-change { font-size: 9pt; font-weight: 700; margin-top: 3px; }
  .pos { color: #16a34a; } .neg { color: #dc2626; }

  /* Insights / Alerts */
  .insight-row { padding: 4px 0; border-bottom: 1px solid #f1f5f9; font-size: 9.5pt; }
  .alert-row { background: #fff7ed; border: 1px solid #fed7aa; border-radius: 5px; padding: 6px 10px; margin: 3px 0; font-size: 9.5pt; color: #c2410c; font-weight: 600; }
  .two-col { display: grid; grid-template-columns: 1fr 1fr; gap: 14px; }

  /* Table */
  table { width: 100%; border-collapse: collapse; font-size: 9pt; }
  thead th { background: #1e3a5f; color: #fff; padding: 7px 8px; text-align: left; font-weight: 700; font-size: 8pt; text-transform: uppercase; letter-spacing: .4px; }
  tbody tr:nth-child(even) { background: #f8fafc; }
  tbody td { padding: 6px 8px; border-bottom: 1px solid #f1f5f9; }

  /* Page break */
  .page-break { page-break-before: always; padding-top: 10px; }
  @media print { .page-break { page-break-before: always; } }
</style>
</head>
<body>

<!-- HEADER -->
<div class="hdr">
  <h1>Kitchen Book — ${cfg.reportName}</h1>
  <div class="sub">Official Report Document</div>
  <div class="meta-grid">
    <div class="meta-item"><div class="mk">Restaurant</div><div class="mv">${cfg.restaurant}</div></div>
    <div class="meta-item"><div class="mk">Branch</div><div class="mv">${cfg.branch}</div></div>
    <div class="meta-item"><div class="mk">Date Range</div><div class="mv">${cfg.dateRange.from} – ${cfg.dateRange.to}</div></div>
    <div class="meta-item"><div class="mk">Generated On</div><div class="mv">${now}</div></div>
    <div class="meta-item"><div class="mk">Generated By</div><div class="mv">${cfg.generatedBy}</div></div>
    <div class="meta-item"><div class="mk">Report Type</div><div class="mv">Detailed Analysis</div></div>
  </div>
</div>

<!-- KPI SUMMARY -->
<div class="section">
  <h3 class="section-title">KPI Summary</h3>
  <div class="kpi-grid">${kpiRows}</div>
</div>

${insightRows || alertRows ? `
<div class="two-col" style="margin-top:18px">
  ${insightRows ? `<div class="section"><h3 class="section-title">Insights</h3>${insightRows}</div>` : ''}
  ${alertRows ? `<div class="section"><h3 class="section-title">Alerts</h3>${alertRows}</div>` : ''}
</div>` : ''}

<!-- DETAILED TABLES -->
${tableSections}

</body>
</html>`;
  }
}
